//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_ТРЗБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cabins()
        {
            this.SeatsInCabins = new HashSet<SeatsInCabins>();
        }
    
        public int Number { get; set; }
        public int ShipNumber { get; set; }
        public int Type { get; set; }
    
        public virtual Ships Ships { get; set; }
        public virtual CabinTypes CabinTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatsInCabins> SeatsInCabins { get; set; }
    }
}
