//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_ТРЗБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routes()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Number { get; set; }
        public int CruiseNumber { get; set; }
        public int ShipNumber { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
    
        public virtual Cruise Cruise { get; set; }
        public virtual Ships Ships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
