//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_ТРЗБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatsInCabins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatsInCabins()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Identifier { get; set; }
        public int CabinNumber { get; set; }
        public int ShipNumber { get; set; }
        public int PlaceNumber { get; set; }
    
        public virtual Cabins Cabins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
