//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_ТРЗБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Number { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public int RouteNumber { get; set; }
        public int SeatIdentifier { get; set; }
    
        public virtual Passengers Passengers { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual SeatsInCabins SeatsInCabins { get; set; }
    }
}
